# Generated by Django 5.2.8 on 2026-04-15 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('sales', '0003_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='sales.sale'),
        ),
    ]
